name = "qr-clock-bot"
main = "cloudflare-worker.js"
compatibility_date = "2024-01-01"
account_id = "770447eb9a0fc2475bd1d61eeb6d2021"

[[kv_namespaces]]
binding = "KV"
id = "65cfc977653d4178a44f700324e798e8"

[triggers]
crons = ["*/2 * * * *"]
